#!/bin/bash

if [ -f "package.json" ]; then
   echo "\"package.json\" not found! Please run this command at the root of the project."
   exit 2
fi

npm install --save-dev eslint-config-react-app babel-eslint@^7.2.3 eslint@^4.1.1 eslint-plugin-flowtype@^2.34.1 eslint-plugin-import@^2.6.0 eslint-plugin-jsx-a11y@^5.1.1 eslint-plugin-react@^7.1.0

echo '{ "extends": "react-app" }' > .eslintrc